### ISSUE TITLE
Not retrieving coverage for HPO case 21364

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/chanjo-report#52]
Hi!
The coverage report for the HPO panel is not loading for case 21364 (timeout).
This happenend before, I don't remember how it was solved.
Best regards,
Malin

**Comment by MUebe** [comment]
Hi! Back from holiday now. Thanks for your work on the issue. Unfortunately, I still get the timeout when I try to load the HPO coverage report. Did I miss anything?

**Comment by northwestwitch** [comment]
> Hi! Back from holiday now. Thanks for your work on the issue. Unfortunately, I still get the timeout when I try to load the HPO coverage report. Did I miss anything?

Hello, I know, that's because we haven't released and deployed the new Scout release with the fix. We are preparing it on these days. You'll get an email from me (Chiara) or Daniel when we release and install the new release, as usual. Sorry for the inconvenience!

**Comment by MUebe** [comment]
Okay, I understand. :)

**Comment by northwestwitch** [comment]
Hello again, after deploying the latest software today the problem should be solved. Thanks again for reporting the issue!
